using System.Diagnostics.CodeAnalysis;
using Content.Client.Guidebook.Controls;
using Content.Client.Guidebook.Richtext;
using Content.Client.UserInterface.ControlExtensions;
using Content.Shared.Chemistry.Reaction;
using Content.Shared.Chemistry.Reagent;
using Content.Shared.EntityEffects.Effects.EntitySpawning;
using JetBrains.Annotations;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client._TP;

/// <summary>
/// Control for embedding a chemical reaction into a guidebook. This is used for Food recipes.
/// </summary>
[UsedImplicitly, GenerateTypedNameReferences]
public sealed partial class GuideReactionEmbed : PanelContainer, IDocumentTag, ISearchableControl
{
    [Dependency] private readonly IPrototypeManager _prototype = default!;
    [Dependency] private readonly ILogManager _logManager = default!;

    private readonly ISawmill _sawmill;

    public GuideReactionEmbed()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        MouseFilter = MouseFilterMode.Stop;
        _sawmill = _logManager.GetSawmill("guidebook.reaction");
    }

    public GuideReactionEmbed(ReactionPrototype reaction) : this()
    {
        GenerateControl(reaction);
    }

    public bool CheckMatchesSearch(string query)
    {
        return this.ChildrenContainText(query);
    }

    public void SetHiddenState(bool state, string query)
    {
        Visible = CheckMatchesSearch(query) ? state : !state;
    }

    public bool TryParseTag(Dictionary<string, string> args, [NotNullWhen(true)] out Control? control)
    {
        control = null;
        if (!args.TryGetValue("Reaction", out var id))
        {
            _sawmill.Error("Reaction embed tag is missing reaction prototype argument");
            return false;
        }

        if (!_prototype.TryIndex<ReactionPrototype>(id, out var reaction))
        {
            _sawmill.Error($"Specified reaction prototype \"{id}\" is not a valid reaction prototype");
            return false;
        }

        GenerateControl(reaction);

        control = this;
        return true;
    }

    private void GenerateControl(ReactionPrototype reaction)
    {
        // We start with a reaction name, marking it up with a guidebook entry.
        var msg = new FormattedMessage();
        msg.AddMarkupOrThrow(Loc.GetString("guidebook-reaction-name", ("name", reaction.Name)));
        ResultName.SetMessage(msg);

        // The reagent reactants
        foreach (var (reagentId, reactant) in reaction.Reactants)
        {
            if (!_prototype.TryIndex<ReagentPrototype>(reagentId, out var reagent))
                continue;

            // Color swatch
            var colorMsg = new FormattedMessage();
            colorMsg.AddMarkupOrThrow(Loc.GetString("guidebook-microwave-reagent-color-display",
                ("color", reagent.SubstanceColor)));

            var colorLabel = new RichTextLabel();
            colorLabel.SetMessage(colorMsg);
            ReactantsGrid.AddChild(colorLabel);

            // The reaction Name and reagents needed
            var nameMsg = new FormattedMessage();
            nameMsg.AddMarkupOrThrow(Loc.GetString("guidebook-reaction-reactant-display",
                ("reagent", reagent.LocalizedName),
                ("amount", reactant.Amount)));
            var nameLabel = new RichTextLabel();
            nameLabel.SetMessage(nameMsg);
            ReactantsGrid.AddChild(nameLabel);
        }

        // The resulting reagent products
        foreach (var (reagentId, amount) in reaction.Products)
        {
            if (!_prototype.TryIndex<ReagentPrototype>(reagentId, out var reagent))
                continue;

            var productMsg = new FormattedMessage();
            productMsg.AddMarkupOrThrow(Loc.GetString("guidebook-reaction-product-display",
                ("reagent", reagent.LocalizedName),
                ("amount", amount)));

            var productLabel = new RichTextLabel();
            productLabel.SetMessage(productMsg);
            ResultContainer.AddChild(productLabel);
        }

        // The actual resulting entity
        foreach (var effect in reaction.Effects)
        {
            if (effect is not SpawnEntity spawnEffect)
                continue;

            if (!_prototype.TryIndex<EntityPrototype>(spawnEffect.Entity, out var entity))
                continue;

            ResultContainer.AddChild(new GuideEntityEmbed(spawnEffect.Entity, false, false));

            var entityMsg = new FormattedMessage();
            entityMsg.AddMarkupOrThrow(Loc.GetString("guidebook-reaction-entity-product-display",
                ("name", entity.Name)));

            var entityLabel = new RichTextLabel();
            entityLabel.SetMessage(entityMsg);
            ResultContainer.AddChild(entityLabel);
        }
    }
}
