using System.Linq;
using Content.Shared.Access;
using Content.Shared.Roles;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._TP14.Access.UI;

[GenerateTypedNameReferences]
public sealed partial class TriesteAccessLevelControl : BoxContainer
{
    [Dependency] private readonly ILogManager _logManager = default!;
    private ISawmill _sawmill = default!;

    public readonly Dictionary<ProtoId<AccessLevelPrototype>, Button> ButtonsList = new();

    // Stores access levels per department for repopulating the grid on selection
    private Dictionary<string, List<ProtoId<AccessLevelPrototype>>> _departmentAccess = new();

    public TriesteAccessLevelControl()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _sawmill = _logManager.GetSawmill("trieste|accesslevelcontrol");
    }

    public void Populate(List<ProtoId<AccessLevelPrototype>> accessLevels, IPrototypeManager prototypeManager)
    {
        AccessGrid.RemoveAllChildren();
        ButtonsList.Clear();
        _departmentAccess.Clear();

        var departments = prototypeManager.EnumeratePrototypes<DepartmentPrototype>()
            .Where(d => !d.EditorHidden)
            .OrderByDescending(d => d.Weight)
            .ThenBy(d => d.ID)
            .ToList();

        // Initialize department buckets
        foreach (var dept in departments)
        {
            _departmentAccess[Loc.GetString(dept.Name)] = new List<ProtoId<AccessLevelPrototype>>();
        }

        var assignedAccess = new HashSet<ProtoId<AccessLevelPrototype>>();

        foreach (var access in accessLevels)
        {
            if (!prototypeManager.TryIndex(access, out var accessLevel))
                continue;

            if (accessLevel.Departments.Count > 0)
            {
                foreach (var deptId in accessLevel.Departments)
                {
                    if (!prototypeManager.TryIndex(deptId, out DepartmentPrototype? dept))
                        continue;

                    var deptName = Loc.GetString(dept.Name);
                    if (!_departmentAccess.ContainsKey(deptName))
                        _departmentAccess[deptName] = new List<ProtoId<AccessLevelPrototype>>();

                    _departmentAccess[deptName].Add(access);

                    assignedAccess.Add(access);
                }
            }

            var button = new Button
            {
                Text = accessLevel.GetAccessLevelName(),
                ToggleMode = true,
            };
            ButtonsList.Add(accessLevel.ID, button);
        }

        // Unassigned access goes to Other
        var unassigned = accessLevels.Where(a => !assignedAccess.Contains(a)).ToList();
        if (unassigned.Count > 0)
            _departmentAccess["Other"] = unassigned;

        // Remove empty departments
        foreach (var key in _departmentAccess.Keys.Where(k => _departmentAccess[k].Count == 0).ToList())
        {
            _departmentAccess.Remove(key);
        }

        _departmentAccess = _departmentAccess
            .OrderBy(kvp => kvp.Key)
            .ToDictionary(kvp => kvp.Key, kvp => kvp.Value);

        if (_departmentAccess.Count > 0)
            PopulateGrid(_departmentAccess.Keys.First());
    }

    public void PopulateGrid(string departmentName)
    {
        AccessGrid.RemoveAllChildren();

        if (!_departmentAccess.TryGetValue(departmentName, out var accessList))
            return;

        foreach (var access in accessList)
        {
            if (ButtonsList.TryGetValue(access, out var button))
                AccessGrid.AddChild(button);
        }
    }

    public void UpdateState(
        List<ProtoId<AccessLevelPrototype>> pressedList,
        List<ProtoId<AccessLevelPrototype>>? enabledList = null)
    {
        foreach (var (accessName, button) in ButtonsList)
        {
            button.Pressed = pressedList.Contains(accessName);
            button.Disabled = !(enabledList?.Contains(accessName) ?? true);
        }
    }

    public IEnumerable<string> GetDepartmentNames() => _departmentAccess.Keys;
}
