using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Content.Server.Database.Migrations.Postgres
{
    /// <inheritdoc />
    public partial class PendingChanges : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(
                "ALTER TABLE profile ADD COLUMN IF NOT EXISTS custom_species_name text NOT NULL DEFAULT '';");

            migrationBuilder.Sql(@"
                CREATE TABLE IF NOT EXISTS star_light_profile (
                    star_light_profile_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    profile_id integer NOT NULL,
                    custom_species_name character varying(32),
                    CONSTRAINT ""FK_star_light_profile_profile_profile_id""
                        FOREIGN KEY (profile_id)
                        REFERENCES profile(profile_id)
                        ON DELETE CASCADE
                );
            ");

            migrationBuilder.Sql(
                "CREATE UNIQUE INDEX IF NOT EXISTS \"IX_star_light_profile_profile_id\" ON star_light_profile(profile_id);");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("DROP TABLE IF EXISTS star_light_profile;");

            migrationBuilder.Sql(
                "ALTER TABLE profile DROP COLUMN IF EXISTS custom_species_name;");
        }
    }
}
