- type: antag
  id: Nukeops
  name: roles-antag-nuclear-operative-name
  antagonist: true
  setPreference: true
  objective: roles-antag-nuclear-operative-objective
  requirements:
  - !type:OverallPlaytimeRequirement
    time: 18000 # 5h
  guides: [ NuclearOperatives ]
  previewStartingGear: SyndicateOperativeGearFull

- type: antag
  id: NukeopsMedic
  name: roles-antag-nuclear-operative-agent-name
  antagonist: true
  setPreference: true
  objective: roles-antag-nuclear-operative-agent-objective
  requirements:
  - !type:OverallPlaytimeRequirement
    time: 18000 # 5h
  - !type:RoleTimeRequirement
    role: JobChemist
    time: 10800 # 3h
  guides: [ NuclearOperatives ]
  previewStartingGear: SyndicateOperativeMedicFull

- type: antag
  id: NukeopsCommander
  name: roles-antag-nuclear-operative-commander-name
  antagonist: true
  setPreference: true
  objective: roles-antag-nuclear-operative-commander-objective
  requirements:
  - !type:OverallPlaytimeRequirement
    time: 18000 # 5h
  - !type:DepartmentTimeRequirement
    department: Security
    time: 18000 # 5h
  # should be changed to nukie playtime when thats tracked (wyci)
  guides: [ NuclearOperatives ]
  previewStartingGear: SyndicateCommanderGearFull

- type: startingGear
  id: SyndicateOperativeGearFullNoUplink
  equipment:
    jumpsuit: ClothingUniformJumpsuitDeathSquad
    back: ClothingBackpackDuffel
    mask: ClothingMaskGasERT
    eyes: ClothingEyesHudSyndicate
    ears: ClothingHeadsetAltCaskie
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterHardsuitERTLeader
    shoes: ClothingShoesBootsCombatFilled
    id: NanotrasenPDA
    pocket1: DoubleEmergencyOxygenTankFilled
    pocket2: TP14BaseUplinkRadioNT #TP
    belt: ClothingBeltMilitaryWebbing
  storage:
    back:
    - TP14WeaponNtBlaster #TP
    - DeathAcidifierImplanter

#Nuclear Operative Gear
- type: startingGear
  id: SyndicateOperativeGearFull
  parent: SyndicateOperativeGearFullNoUplink
  equipment:
    pocket2: BaseUplinkRadio40TC

- type: chameleonOutfit
  id: NukeopsOutfit
  name: roles-antag-nuclear-operative-name
  startingGear: SyndicateOperativeGearFullNoUplink
  icon: "JobIconSyndicate"
  equipment:
    head: ClothingHeadHelmetHardsuitSyndie
    neck: ClothingNeckScarfStripedSyndieRed

#Nuclear Operative Commander Gear
- type: startingGear
  id: SyndicateCommanderGearFull
  parent: SyndicateOperativeGearFull
  equipment:
    outerClothing: ClothingOuterHardsuitERTLeader
  inhand:
  - NukeOpsDeclarationOfWar

- type: chameleonOutfit
  id: NukeopsCommanderOutfit
  name: roles-antag-nuclear-operative-commander-name
  startingGear: SyndicateCommanderGearFull
  icon: "JobIconSyndicate"
  equipment:
    head: ClothingHeadHelmetHardsuitSyndieCommander
    neck: ClothingNeckScarfStripedSyndieGreen

#Nuclear Operative Medic Gear
- type: startingGear
  id: SyndicateOperativeMedicFull
  parent: SyndicateOperativeGearFull
  equipment:
    eyes: ClothingEyesHudSyndicateAgent
    outerClothing: ClothingOuterHardsuitERTMedical
    shoes: ClothingShoesBootsMagSyndie
    id: NanotrasenPDA
    belt: ClothingBeltMilitaryWebbingMedFilled
  storage:
    back:
    - SyndiHypo
    - SawAdvanced
    - Cautery
    - CombatKnife
    - TP14WeaponNtBlaster #TP
    - HandheldHealthAnalyzer
    - CombatMedipen
    - DeathAcidifierImplanter

- type: chameleonOutfit
  id: NukeopsMedicOutfit
  name: roles-antag-nuclear-operative-agent-name
  startingGear: SyndicateOperativeMedicFull
  icon: "JobIconSyndicate"
  equipment:
    head: ClothingHeadHelmetHardsuitSyndieMedic
    neck: ClothingNeckScarfStripedLightBlue

#Lone Operative Gear
- type: startingGear
  id: SyndicateLoneOperativeGearFull
  parent: SyndicateOperativeGearFull
  equipment:
    pocket2: BaseUplinkRadio60TC
