- type: entity
  id: TP14ColdplateMachineCircuitboard
  parent: BaseMachineCircuitboard
  name: coldplate machine board
  description: A machine printed circuit board for a coldplate.
  components:
    - type: MachineBoard
      prototype: TP14ChemistryColdplate
      stackRequirements:
        Capacitor: 2
        Glass: 1
