- type: entity
  id: TP14ColdplateMachineCircuitboard
  parent: BaseMachineCircuitboard
  name: coldplate machine board
  description: A machine printed circuit board for a coldplate.
  components:
    - type: MachineBoard
      prototype: TP14ChemistryColdplate
      stackRequirements:
        Manipulator: 2
        Glass: 1

- type: entity
  id: JellidPortableScrubberMachineCircuitBoard
  parent: BaseMachineCircuitboard
  name: jellid portable scrubber machine board
  description: A machine printed circuit board for a jellid portable scrubber.
  components:
  - type: Sprite
    state: engineering
  - type: MachineBoard
    prototype: JellidPortableScrubber
    stackRequirements:
      Manipulator: 3
      Cable: 5
      Glass: 2

- type: entity
  id: IncubatorMachineCircuitboard
  parent: BaseMachineCircuitboard
  name: incubator machine board
  description: A machine printed circuit board for an incubator.
  components:
    - type: Sprite
      state: medical
    - type: MachineBoard
      prototype: MachineIncubator
      stackRequirements:
        Manipulator: 2
        Glass: 1
        Steel: 1

- type: entity
  id: TP14SMESAdvancedMachineCircuitboard
  parent: BaseMachineCircuitboard
  name: trieste's advanced SMES machine board
  description: A machine printed circuit board for a trieste-speciifc Advanced SMES.
  components:
  - type: Sprite
    sprite: Objects/Misc/module.rsi
    state: power_mod
  - type: MachineBoard
    prototype: TP14SMESAdvancedEmpty
    stackRequirements:
      Manipulator: 3
      CableHV: 30
    componentRequirements:
      PowerCell:
        amount: 8
        defaultPrototype: PowerCellMedium
